# Generated by Django 4.2.7 on 2025-12-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('key', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('verse', 'Verse'), ('chorus', 'Chorus'), ('bridge', 'Bridge'), ('prechorus', 'Pre-chorus'), ('intro', 'Intro'), ('outro', 'Outro'), ('tag', 'Tag'), ('other', 'Other')], default='verse', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
