# Generated by Django 4.2.7 on 2025-12-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bible_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsection',
            name='section_type',
            field=models.CharField(choices=[('verse', 'Verse'), ('chorus', 'Chorus'), ('bridge', 'Bridge'), ('prechorus', 'Pre-chorus'), ('intro', 'Intro'), ('outro', 'Outro'), ('tag', 'Tag'), ('other', 'Other'), ('bible', 'Bible Passage')], default='verse', max_length=20),
        ),
    ]
